<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="slambot">

<xacro:property name = "wheel_radius" value = "0.1" />
<xacro:property name = "wheel_width" value = "0.075" />
<xacro:property name = "wheel_mass" value = "10.0" />

<xacro:property name = "base_width" value = "0.4" />
<xacro:property name = "base_length" value = "0.5" />
<xacro:property name = "base_height" value = "0.05" />
<xacro:property name = "base_mass" value = "10000.0" />

<xacro:property name = "laser_mass" value = "0.1" />
<xacro:property name = "laser_height" value = "0.1" />
<xacro:property name = "laser_radius" value = "0.1" />

	<link name = "base_link" >
		<inertial>
			<mass value = "${base_mass}" />
			<origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0" />
			<inertia ixx = "${base_mass*(base_length*base_length+base_height*base_height)/12}"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "${base_mass*(base_width*base_width+base_height*base_height)/12}"
					 iyz = "0.0"
					 izz = "${base_mass*(base_length*base_length+base_width*base_width)/12}" />
		</inertial>

		<visual name = "base_link_visual" >
			<origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0" />
			<geometry>
				<box size = "${base_width} ${base_length} ${base_height}" />
			</geometry>
		</visual>

		<collision name = "base_link_collision" >
			<origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0" />
			<geometry>
				<box size = "${base_width} ${base_length} ${base_height}" />
			</geometry>
		</collision>
	</link>

	<link name = "laser_link" >
		<inertial>
			<mass value = "${laser_mass}" />
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<inertia ixx = "0.0"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0" />
		</inertial>

		<visual name = "laser_link_visual" >
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<geometry>
				<cylinder length = "${laser_height}" radius = "${laser_radius}" />
			</geometry>
		</visual>

		<collision name = "laser_link_collision" >
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<geometry>
				<cylinder length = "${laser_height}" radius = "${laser_radius}" />
			</geometry>
		</collision>
	</link>

	<link name = "front_right_wheel_link" >
		<inertial>
			<mass value = "${wheel_mass}" />
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<inertia ixx = "${base_mass*(wheel_radius*wheel_radius)/2}"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0" />
		</inertial>

		<visual name = "front_right_wheel_visual" >
			<origin xyz = "0 0 0" rpy = "0 1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</visual>

		<collision name = "front_right_wheel_collision" >
			<origin xyz = "0 0 0" rpy = "0 1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</collision>
	</link>

	<link name = "front_left_wheel_link" >
		<inertial>
			<mass value = "${wheel_mass}" />
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<inertia ixx = "${base_mass*(wheel_radius*wheel_radius)/2}"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0" />
		</inertial>

		<visual name = "front_left_wheel_visual" >
			<origin xyz = "0 0 0" rpy = "0 -1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</visual>

		<collision name = "front_left_wheel_collision" >
			<origin xyz = "0 0 0" rpy = "0 -1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</collision>
	</link>

	<link name = "back_right_wheel_link" >
		<inertial>
			<mass value = "${wheel_mass}" />
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<inertia ixx = "${base_mass*(wheel_radius*wheel_radius)/2}"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0" />
		</inertial>

		<visual name = "back_right_wheel_visual" >
			<origin xyz = "0 0 0" rpy = "0 1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</visual>

		<collision name = "back_right_wheel_collision" >
			<origin xyz = "0 0 0" rpy = "0 1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</collision>
	</link>

	<link name = "back_left_wheel_link" >
		<inertial>
			<mass value = "${wheel_mass}" />
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<inertia ixx = "${base_mass*(wheel_radius*wheel_radius)/2}"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0" />
		</inertial>

		<visual name = "back_left_wheel_visual" >
			<origin xyz = "0 0 0" rpy = "0 -1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</visual>

		<collision name = "back_left_wheel_collision" >
			<origin xyz = "0 0 0" rpy = "0 -1.571 0" />
			<geometry>
				<cylinder length = "${wheel_width}" radius = "${wheel_radius}" />
			</geometry>
		</collision>
	</link>

	<joint name = "laser_joint" type = "revolute" >
		<parent link = "base_link" />
		<child link = "laser_link" />
		<origin xyz = "0 ${base_length/2-laser_radius} ${wheel_radius+laser_height/2+base_height/2}" rpy = "0 0 0" />
		<axis xyz = "0 0 1" />
		<limit lower = "0.0" upper = "0.0" velocity = "0.0" effort = "0.0" />
	</joint>

	<joint name = "front_right_wheel_joint" type = "continuous" >
		<parent link = "base_link" />
		<child link = "front_right_wheel_link" />
		<origin xyz = "${base_width/2+wheel_width/2} ${base_length/2-wheel_radius} ${wheel_radius}" rpy = "0 0 0" />
		<axis xyz = "-1 0 0" />
	</joint>

	<joint name = "front_left_wheel_joint" type = "continuous" >
		<parent link = "base_link" />
		<child link = "front_left_wheel_link" />
		<origin xyz = "-${base_width/2+wheel_width/2} ${base_length/2-wheel_radius} ${wheel_radius}" rpy = "0 0 0" />
		<axis xyz = "-1 0 0" />
	</joint>

	<joint name = "back_right_wheel_joint" type = "continuous" >
		<parent link = "base_link" />
		<child link = "back_right_wheel_link" />
		<origin xyz = "${base_width/2+wheel_width/2} -${base_length/2-wheel_radius} ${wheel_radius}" rpy = "0 0 0" />
		<axis xyz = "-1 0 0" />
	</joint>

	<joint name = "back_left_wheel_joint" type = "continuous" >
		<parent link = "base_link" />
		<child link = "back_left_wheel_link" />
		<origin xyz = "-${base_width/2+wheel_width/2} -${base_length/2-wheel_radius} ${wheel_radius}" rpy = "0 0 0" />
		<axis xyz = "-1 0 0" />
	</joint>

	<transmission name = "front_right_wheel_motor" >
	    <type> hardware_interface </type>
    	<joint name= "front_right_wheel_joint" >
      		<hardwareInterface> hardware_interface/VelocityJointInterface </hardwareInterface>
    	</joint>
    	<actuator name = "front_right_wheel_joint" >
      		<hardwareInterface> VelocityJointInterface </hardwareInterface>
      		<mechanicalReduction> 1 </mechanicalReduction>
    	</actuator>
    </transmission>

    <transmission name = "front_left_wheel_motor" >
	    <type> hardware_interface </type>
    	<joint name = "front_left_wheel_joint" >
      		<hardwareInterface> hardware_interface/VelocityJointInterface </hardwareInterface>
    	</joint>
    	<actuator name = "front_left_wheel_joint" >
      		<hardwareInterface> VelocityJointInterface </hardwareInterface>
      		<mechanicalReduction> 1 </mechanicalReduction>
    	</actuator>
    </transmission>

	<transmission name = "back_right_wheel_motor" >
	    <type> hardware_interface </type>
    	<joint name= "back_right_wheel_joint" >
      		<hardwareInterface> hardware_interface/VelocityJointInterface </hardwareInterface>
    	</joint>
    	<actuator name = "back_right_wheel_joint" >
      		<hardwareInterface> VelocityJointInterface </hardwareInterface>
      		<mechanicalReduction> 1 </mechanicalReduction>
    	</actuator>
    </transmission>

    <transmission name = "back_left_wheel_motor" >
	    <type> hardware_interface </type>
    	<joint name = "back_left_wheel_joint" >
      		<hardwareInterface> hardware_interface/VelocityJointInterface </hardwareInterface>
    	</joint>
    	<actuator name = "back_left_wheel_joint" >
      		<hardwareInterface> VelocityJointInterface </hardwareInterface>
      		<mechanicalReduction> 1 </mechanicalReduction>
    	</actuator>
    </transmission>

	<gazebo>
		<static> false </static>

		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace> /slambot </robotNamespace>
		</plugin>
	</gazebo>

	<gazebo reference = "laser_link">
		<sensor type="ray" name="laser">
			<pose> 0 0.01 ${laser_height/2} 0 0 1.571 </pose>
			<visualize> false </visualize>
			<update_rate> 40 </update_rate>
			<ray>
		    	<scan>
		      		<horizontal>
		        		<samples>720</samples>
		        		<resolution>1</resolution>
		        		<min_angle>-1.570796</min_angle>
		        		<max_angle>1.570796</max_angle>
		      		</horizontal>
		    	</scan>
		    	
		    	<range>
		      		<min>0.10</min>
		      		<max>30.0</max>
		      		<resolution>0.01</resolution>
		    	</range>
		    	
		    	<noise>
		      		<type>gaussian</type>
		      		<mean>0.0</mean>
		      		<stddev>0.01</stddev>
		    	</noise>
		  	</ray>

			<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
				<topicName> /scan </topicName>
				<frameName> base_link </frameName>
			</plugin>
		</sensor>
  	</gazebo>

</robot>