obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.25,-0.2], [-0.25,0.2], [0.25,-0.2], [0.25,0.2]]
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}