obstacle_range: 5
raytrace_range: 3
footprint: [[-0.325,-0.2], [-0.325,0.2], [0.325,-0.2], [0.325,0.2]]
inflation_radius: 0.25

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}