slambot:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 40

  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['front_left_wheel_joint','back_left_wheel_joint']
    right_wheel: ['front_right_wheel_joint','back_right_wheel_joint']
    wheel_radius: 0.1
    wheel_separation: 0.475
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    publish_rate: 40